### ISSUE TITLE
LocalIn correct?

### ISSUE THREAD

**Issue by Sciss** [sonoro1234/Lua2SC#1]
I'm not sure about how you define LocalIn: 

https://github.com/sonoro1234/Lua2SC/blob/c03316dc75d9956a00e71604b7e9b1a0265294cb/lua2SC/lua/sc/declareugens.lua#L7799

What does `LocalIn:MultiNew{1,numChannels,default}` actually do? Stumbling across a problem in ScalaCollider, I noticed that the UGen must now initialise exactly one input slot per output slot, perhaps you check if that is the case here. See: https://github.com/supercollider/supercollider/issues/2363

**Comment by sonoro1234** [comment]
UGen definitions are on the automatically generated https://github.com/sonoro1234/Lua2SC/blob/c03316dc75d9956a00e71604b7e9b1a0265294cb/lua2SC/lua/sc/declareugens4.lua
but some UGens are then modified in https://github.com/sonoro1234/Lua2SC/blob/c03316dc75d9956a00e71604b7e9b1a0265294cb/lua2SC/lua/sc/synthdefsc.lua

LocalIn is

```
LocalIn=MultiOutUGen:new{name='LocalIn'}
function LocalIn.kr(numChannels)
    numChannels=numChannels or 1;
    return LocalIn:MultiNew{1,numChannels}
end
function LocalIn.ar(numChannels)
    numChannels=numChannels or 1;
    return LocalIn:MultiNew{2,numChannels}
end
```

It was correct last time I used it ;-)
But surely I only use LocalIn.ar

I am not aware of the issues you were reporting I should investigate about them

Best
victor

**Comment by sonoro1234** [comment]
You made me realize that the automatically generated UGen definition was ok (just for one channel default) but not the manual replacement (which in fact was older) and has no default
Thanks

**Comment by sonoro1234** [comment]
Just corrected
