### ISSUE TITLE
Cant boot SC

### ISSUE THREAD

**Issue by nagolove** [sonoro1234/Lua2SC#5]
Hello! I could not hear any sound from example file.
```
$uname -a
Linux legion 5.7.15-1-MANJARO #1 SMP PREEMPT Tue Aug 11 15:00:37 UTC 2020 x86_64 GNU/Linux
```
I run JACK from QjackCtl tool. I had installed SuperCollider in my system and also I compiled supernova from sources and put it to Lua2SCinstall/SuperCollider. I tried to `Supercollider->Boot SC` and got 
`SCTCP waiting for server	nil	connection refused` in program console. Also I tried to `Boot SC internal` but it has same result.

**Comment by sonoro1234** [comment]
Did you try with LuaSC provided in releases (v0.3)? (It already has supernova inside)
What does SC Log say?

`server nil` Could mean that your settings for Sc port are empty (should be 57110 for example)
You can see them at Debug->Settings
To get defaults again there, you should close Lua2SC app and delete `Lua2SCinstall/lua2SC/settings.txt`. When reopening Lua2SC default settings are back.

Any update on this?

**Comment by nagolove** [comment]
Now I tried prebuilt-in release [0.3](https://github.com/sonoro1234/Lua2SC/releases/download/v0.3/Lua2SC_0.3-linux64.tar.gz)
![Screenshot_2020-09-14_18-20-17](https://user-images.githubusercontent.com/12562619/93085214-e75ab000-f69d-11ea-9ff0-43af027a977a.png)
I open file `simple_theme.lua`, boot SC and press F6.
SC Log
```
begin sc loop ....
Supernova booting
Found 12 LADSPA plugins
reading cache file: /home/testuser/.VSTPlugin/plugins.ini
done reading cache file
server finished
SCProcess_Loop finalizer:
after normal return
finalizer ok
```
Log
```
InitSCCOMM	
initsendtcp	
xpcallerror:...user/Downloads/Lua2SC_portable/lua2SC/lua/sc/sc_comm.lua:98: tcp es nulo	
staklevel	inf	
is require?	true	
is dofile?	false	
is loadfile?	false	
SCRIPT: finalizer after normal return	
SCRIPT: finalizer ok	
SCTCP waiting for server	nil	connection refused	
SCTCP waiting for server	nil	connection refused	
SCTCP waiting for server	nil	connection refused	
SCTCP waiting for server	nil	connection refused	
SCTCP waiting for server	nil	connection refused	
SCTCP waiting for server	nil	connection refused	
SCTCP waiting for server	nil	connection refused	
exit on udpsclinda	
TCPSC: ReceiveLoop finalizer:	
TCPSC: after normal return	
```
Also I did'not see any output devices in QJackControl graph view.

**Comment by sonoro1234** [comment]
SCLog says `server finished` without any error explanation. This is why connection is refused.
Try to delete LADSPA UGen and VSTPlugin to see if server is not finished

Did it work?

**Comment by sonoro1234** [comment]
> boot SC and press F6.

Did you wait for server booted between bootSC and F6?
bootSC must succed before using F6.

bootSC not succeding could be several things (not Lua2SC issue but scsynt or supernova issue:  folder permissions, UGen failing for some reason, ...)

**Comment by sonoro1234** [comment]
Too long without answer
